services:
  app:
    build: .
    volumes:
      - ./app:/app 
    command: npm run dev 
    depends_on:
      - redis
  redis:
    image: redis
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped